# TCL File Generated by Component Editor 22.1
# Fri Sep 08 21:12:52 CEST 2023
# DO NOT MODIFY


# 
# DMAC "DMAC" v2.0
# biw 2023.09.08.21:12:52
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module DMAC
# 
set_module_property DESCRIPTION ""
set_module_property NAME DMAC
set_module_property VERSION 2.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR biw
set_module_property DISPLAY_NAME DMAC
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL DMAC_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file DMAC_top.vhd VHDL PATH ../src/DMAC_top.vhd
add_fileset_file ShowAheadFifo.vhd VHDL PATH ShowAheadFifo.vhd


# 
# parameters
# 


# 
# module assignments
# 
set_module_assignment embeddedsw.dts.compatible dma_controller
set_module_assignment embeddedsw.dts.group wzperiphs
set_module_assignment embeddedsw.dts.vendor biw


# 
# display items
# 


# 
# connection point avm_read_master
# 
add_interface avm_read_master avalon start
set_interface_property avm_read_master addressUnits SYMBOLS
set_interface_property avm_read_master associatedClock i_clk
set_interface_property avm_read_master associatedReset i_reset
set_interface_property avm_read_master bitsPerSymbol 8
set_interface_property avm_read_master burstOnBurstBoundariesOnly false
set_interface_property avm_read_master burstcountUnits WORDS
set_interface_property avm_read_master doStreamReads false
set_interface_property avm_read_master doStreamWrites false
set_interface_property avm_read_master holdTime 0
set_interface_property avm_read_master linewrapBursts false
set_interface_property avm_read_master maximumPendingReadTransactions 0
set_interface_property avm_read_master maximumPendingWriteTransactions 0
set_interface_property avm_read_master readLatency 0
set_interface_property avm_read_master readWaitTime 1
set_interface_property avm_read_master setupTime 0
set_interface_property avm_read_master timingUnits Cycles
set_interface_property avm_read_master writeWaitTime 0
set_interface_property avm_read_master ENABLED true
set_interface_property avm_read_master EXPORT_OF ""
set_interface_property avm_read_master PORT_NAME_MAP ""
set_interface_property avm_read_master CMSIS_SVD_VARIABLES ""
set_interface_property avm_read_master SVD_ADDRESS_GROUP ""

add_interface_port avm_read_master avm_read_master_address address Output 32
add_interface_port avm_read_master avm_read_master_read read Output 1
add_interface_port avm_read_master avm_read_master_readdata readdata Input 32
add_interface_port avm_read_master avm_read_master_waitrequest waitrequest Input 1


# 
# connection point avm_write_master
# 
add_interface avm_write_master avalon start
set_interface_property avm_write_master addressUnits SYMBOLS
set_interface_property avm_write_master associatedClock i_clk
set_interface_property avm_write_master associatedReset i_reset
set_interface_property avm_write_master bitsPerSymbol 8
set_interface_property avm_write_master burstOnBurstBoundariesOnly false
set_interface_property avm_write_master burstcountUnits WORDS
set_interface_property avm_write_master doStreamReads false
set_interface_property avm_write_master doStreamWrites false
set_interface_property avm_write_master holdTime 0
set_interface_property avm_write_master linewrapBursts false
set_interface_property avm_write_master maximumPendingReadTransactions 0
set_interface_property avm_write_master maximumPendingWriteTransactions 0
set_interface_property avm_write_master readLatency 0
set_interface_property avm_write_master readWaitTime 1
set_interface_property avm_write_master setupTime 0
set_interface_property avm_write_master timingUnits Cycles
set_interface_property avm_write_master writeWaitTime 0
set_interface_property avm_write_master ENABLED true
set_interface_property avm_write_master EXPORT_OF ""
set_interface_property avm_write_master PORT_NAME_MAP ""
set_interface_property avm_write_master CMSIS_SVD_VARIABLES ""
set_interface_property avm_write_master SVD_ADDRESS_GROUP ""

add_interface_port avm_write_master avm_write_master_address address Output 32
add_interface_port avm_write_master avm_write_master_writedata writedata Output 32
add_interface_port avm_write_master avm_write_master_write write Output 1
add_interface_port avm_write_master avm_write_master_waitrequest waitrequest Input 1


# 
# connection point avs_csr
# 
add_interface avs_csr avalon end
set_interface_property avs_csr addressUnits WORDS
set_interface_property avs_csr associatedClock i_clk
set_interface_property avs_csr associatedReset i_reset
set_interface_property avs_csr bitsPerSymbol 8
set_interface_property avs_csr burstOnBurstBoundariesOnly false
set_interface_property avs_csr burstcountUnits WORDS
set_interface_property avs_csr explicitAddressSpan 0
set_interface_property avs_csr holdTime 0
set_interface_property avs_csr linewrapBursts false
set_interface_property avs_csr maximumPendingReadTransactions 0
set_interface_property avs_csr maximumPendingWriteTransactions 0
set_interface_property avs_csr readLatency 0
set_interface_property avs_csr readWaitTime 1
set_interface_property avs_csr setupTime 0
set_interface_property avs_csr timingUnits Cycles
set_interface_property avs_csr writeWaitTime 0
set_interface_property avs_csr ENABLED true
set_interface_property avs_csr EXPORT_OF ""
set_interface_property avs_csr PORT_NAME_MAP ""
set_interface_property avs_csr CMSIS_SVD_VARIABLES ""
set_interface_property avs_csr SVD_ADDRESS_GROUP ""

add_interface_port avs_csr avs_csr_address address Input 2
add_interface_port avs_csr avs_csr_readdata readdata Output 32
add_interface_port avs_csr avs_csr_writedata writedata Input 32
add_interface_port avs_csr avs_csr_write write Input 1
set_interface_assignment avs_csr embeddedsw.configuration.isFlash 0
set_interface_assignment avs_csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avs_csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avs_csr embeddedsw.configuration.isPrintableDevice 0


# 
# connection point irq
# 
add_interface irq interrupt end
set_interface_property irq associatedAddressablePoint ""
set_interface_property irq associatedClock i_clk
set_interface_property irq associatedReset i_reset
set_interface_property irq bridgedReceiverOffset ""
set_interface_property irq bridgesToReceiver ""
set_interface_property irq ENABLED true
set_interface_property irq EXPORT_OF ""
set_interface_property irq PORT_NAME_MAP ""
set_interface_property irq CMSIS_SVD_VARIABLES ""
set_interface_property irq SVD_ADDRESS_GROUP ""

add_interface_port irq irq irq Output 1


# 
# connection point i_clk
# 
add_interface i_clk clock end
set_interface_property i_clk clockRate 100000000
set_interface_property i_clk ENABLED true
set_interface_property i_clk EXPORT_OF ""
set_interface_property i_clk PORT_NAME_MAP ""
set_interface_property i_clk CMSIS_SVD_VARIABLES ""
set_interface_property i_clk SVD_ADDRESS_GROUP ""

add_interface_port i_clk i_clk clk Input 1


# 
# connection point i_reset
# 
add_interface i_reset reset end
set_interface_property i_reset associatedClock i_clk
set_interface_property i_reset synchronousEdges DEASSERT
set_interface_property i_reset ENABLED true
set_interface_property i_reset EXPORT_OF ""
set_interface_property i_reset PORT_NAME_MAP ""
set_interface_property i_reset CMSIS_SVD_VARIABLES ""
set_interface_property i_reset SVD_ADDRESS_GROUP ""

add_interface_port i_reset i_reset reset Input 1

